<a href="https://colab.research.google.com/github/ishleenkaur256/ai-learning-journey/blob/main/Day_1_and_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
c=np.array([1,2,3])

In [ ]:
print(c)

array([1, 2, 3])

In [ ]:
c.shape

(3,)

In [ ]:
m=[[1,2],[3,4]]
print(m)

[[1, 2], [3, 4]]


In [ ]:
d=np.array([4,5,6])
print(d)

[4 5 6]


In [ ]:
e=np.dot(c,d)
print(e)

32


In [3]:
a=np.array([1,2])
a

array([1, 2])

In [4]:
print(2*a)#scalar mul

[2 4]


In [5]:
print(a.T)

[1 2]
